# Geocoding Loan Dataset

In [1]:
import os
import sys
sys.path.append('../')

import pandas as pd
import sqlalchemy as sqla
from sqlalchemy import create_engine

SBA_DWH = os.getenv('SBA_DWH')
engine = create_engine(SBA_DWH)

from utilities import geocoder

In [2]:
# This will be abstracted/replaced later (possibly reading from URI)
with engine.begin() as conn:
    df = pd.read_sql_table('sba_sfdo', conn, 'stg_analytics')
df['address'] = df.borr_street + ', ' + df.borr_city + ', ' + df.borr_state + ', ' + df.borr_zip.map(str)

In [4]:
df = geocoder.geocode(df=df)

549 GARCIA AVENUE, LOTS 6,7, PITTSBURG, CA, 94565
0
38.0137447 -121.8870177
7755 PARDEE LANE, STE E, OAKLAND, CA, 94621
1
37.7429799 -122.2059938
1985 TEXAS STREETG, FAIRFIELD, CA, 94533
2
38.2492573 -122.0499788
182 TOPAZ STREET, MILPITAS, CA, 95035
3
37.4283725 -121.898816
508 TASMAN, SUNNYVALE, CA, 94089
4
37.4033173 -122.0122518
1181 QUARRY LAND 300, PLEASANTON, CA, 94566
5
37.6706161 -121.8653105
541 DIVISION STREET, CAMPBELL, CA, 95008
6
37.2632072 -121.9593414
15900-15906 CONCORD CIRCLE, MORGAN HILL, CA, 95037
7
37.1140874 -121.6357283
1681-1697 INDUSTRIAL ROAD, SAN CARLOS, CA, 94070
8
37.4991205 -122.2415946
2223 FOURTH STREET, EUREKA, CA, 95501
9
40.805091 -124.147678

In [5]:
df.head()

,program,borr_name,borr_street,borr_city,borr_state,borr_zip,gross_approval,approval_date,approval_fiscal_year,first_disbursement_date,...,bank_name,bank_street,bank_city,bank_state,bank_zip,sba_guaranteed_approval,revolver_status,address,latitudes,longitudes
0,504,BAY AREA DRILLING,"549 GARCIA AVENUE, LOTS 6,7",PITTSBURG,CA,94565,190000,1990-10-11,1991,1990-12-12,...,None,None,None,None,None,NaN,NaN,"549 GARCIA AVENUE, LOTS 6,7, PITTSBURG, CA, 94565",38.013745,-121.887018
1,504,"ARCHITECTURAL ART MFG, INC","7755 PARDEE LANE, STE E",OAKLAND,CA,94621,750000,1990-10-31,1991,1991-09-11,...,None,None,None,None,None,NaN,NaN,"7755 PARDEE LANE, STE E, OAKLAND, CA, 94621",37.742980,-122.205994
2,504,"GREEN VALLEY FOODS, INC.",1985 TEXAS STREETG,FAIRFIELD,CA,94533,297000,1990-12-17,1991,NaT,...,None,None,None,None,None,NaN,NaN,"1985 TEXAS STREETG, FAIRFIELD, CA, 94533",38.249257,-122.049979
3,504,"DIGICOM SYSTEMS, INC.",182 TOPAZ STREET,MILPITAS,CA,95035,750000,1990-12-31,1991,1991-03-13,...,None,None,None,None,None,NaN,NaN,"182 TOPAZ STREET, MILPITAS, CA, 95035",37.428373,-121.898816
4,504,"PATSON'S PRESS, INC.",508 TASMAN,SUNNYVALE,CA,94089,750000,1991-03-05,1991,1991-07-17,...,None,None,None,None,None,NaN,NaN,"508 TASMAN, SUNNYVALE, CA, 94089",37.403317,-122.012252